# Meta Arguments: What job? What train .py file? Base config? Where to store?
meta_job_args:
    project_name: "algo"
    experiment_type: "hyperparameter-search"
    base_train_fname: "run_autosklearn.py"
    base_train_config: "configs/train/wb/auto_resnet50.json"
    experiment_dir: "experiments/wb/auto_resnet50/"

# Parameters specific to the hyperparameter search
param_search_args:
    search_logging:
        reload_log: False
        verbose_log: True
        max_objective: True
        problem_type: "best"
        eval_metrics:
            - "r2_score"
            - "corr_mean"
            - "mse_mean"
            - "mae_mean"
    search_resources:
        num_search_batches: 1
        num_evals_per_batch: 10
        num_seeds_per_eval: 1
    search_config:
        search_type: "grid"
        search_schedule: "sync"
        search_params:
            categorical:
                roi_type:
                    - 'WB'
                subject_id:
                    - 'sub01'
                    - 'sub02'
                    - 'sub03'
                    - 'sub04'
                    - 'sub05'
                    - 'sub06'
                    - 'sub07'
                    - 'sub08'
                    - 'sub09'
                    - 'sub10'

# Parameters specific to an individual job
single_job_args:
    job_name: "algo"
    num_gpus: 0
    num_logical_cores: 5
    log_file: "log"
    err_file: "err"
    env_name: "algonauts"
    time_per_job: "05:00:00"
