# Meta Arguments: What job? What train .py file? Base config? Where to store?
meta_job_args:
    project_name: "algo"
    experiment_type: "hyperparameter-search"
    base_train_fname: "run_bayes_opt.py"
    base_train_config: "configs/train/roi/more_layers/pls_pca_75_simclr_r50_mean.json"
    experiment_dir: "experiments/roi/more_layers/pls_pca_75_simclr_r50_mean/"

# Parameters specific to the hyperparameter search
param_search_args:
    search_logging:
        reload_log: False
        verbose_log: True
        max_objective: True
        problem_type: "best"
        eval_metrics:
            - "best_bo_score"
            - "mse_mean"
            - "mae_mean"
    search_resources:
        num_search_batches: 1
        num_evals_per_batch: 90
        num_seeds_per_eval: 1
    search_config:
        search_type: "grid"
        search_schedule: "sync"
        search_params:
            categorical:
                roi_type:
                    - 'LOC'
                    - 'FFA'
                    - 'STS'
                    - 'EBA'
                    - 'PPA'
                    - 'V1'
                    - 'V2'
                    - 'V3'
                    - 'V4'
                subject_id:
                    - 'sub01'
                    - 'sub02'
                    - 'sub03'
                    - 'sub04'
                    - 'sub05'
                    - 'sub06'
                    - 'sub07'
                    - 'sub08'
                    - 'sub09'
                    - 'sub10'

# Parameters specific to an individual job
single_job_args:
    job_name: "algo"
    num_gpus: 0
    num_logical_cores: 2
    log_file: "log"
    err_file: "err"
    env_name: "algonauts"
    time_per_job: "01:00:00"
    exclude_nodes:
        - "cognition13"

# Parameters for the pre-processing job
pre_processing_args:
    processing_fname: "run_features.py"
    processing_job_args:
        num_logical_cores: 10
        num_gpus: 1
        env_name: "algonauts"
        time_per_job: "01:00:00"
    extra_cmd_line_input:
        model_type: "simclr_r50_2x_sk1_100pct"
        sampling_rate: 2
        trafo_type: "pca"
        num_components: 75
